id: IC3344ABD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:35:56+00:00'
last_modified: '2022-06-07T16:34:05.411461+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4460
  title: རྣམ་སྲས་ཀྱི་བུམ་སྒྲུབ་དང་གཡང་འགུགས་ཀྱི་ཆོ་ག་དགོས་འདོད་ཆར་འབེབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    885B:
      image_group_id: I1KG4584
      title: ''
      total_pages: 74
      order: 1
      base_file: 885B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
