id: P002958
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:30:52.906256
source_metadata:
  id: bdr:W1KG4460
  title: རྣམ་སྲས་ཀྱི་བུམ་སྒྲུབ་དང་གཡང་འགུགས་ཀྱི་ཆོ་ག་དགོས་འདོད་ཆར་འབེབས
  author: ''
  volumes:
    c390aa3595964c9189b426ce75fe7e22:
      image_group_id: I1KG4584
      title: ''
      volume_number: 1
      total_pages: 74
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
